var foodItems = {
    'items':[
        {
            'name':'potato1',
            'src':'potato1_062.png',
            'startX': 100,
            'startY':100,
            'startAngle':90,
            'layer':2,
            'cellWidth':60,
            'cellHeight':170,
            'index':0,
            'frames':[{
                 'name':'uncooked',
                 'xOffset':0,
                 'yOffset':0
                },
                {
                 'name':'cooked',
                 'xOffset':60,
                 'yOffset':0
                },
                {
                 'name':'peeled1',
                 'xOffset':120,
                 'yOffset':0
                },
                {
                 'name':'peeled2',
                 'xOffset':180,
                 'yOffset':0
                },
                {
                 'name':'peeled3',
                 'xOffset':240,
                 'yOffset':0
                },
                {
                 'name':'peeled4',
                 'xOffset':300,
                 'yOffset':0
                },
            ],
            'initital':'uncooked'
            
        }
        ,{
            'name':'potato2',
            'src':'potato3_06.png',
            'startX': 200,
            'startY':100,
            'startAngle':0,
            'layer':2,
            'cellWidth':66,
            'cellHeight':117,
            'index':0,
            'frames':[{
                 'name':'uncooked',
                 'xOffset':0,
                 'yOffset':0
                },
                {
                 'name':'cooked',
                 'xOffset':66,
                 'yOffset':0
                },
                {
                 'name':'peeled1',
                 'xOffset':132,
                 'yOffset':0
                },
                {
                 'name':'peeled2',
                 'xOffset':198,
                 'yOffset':0
                },
                {
                 'name':'peeled3',
                 'xOffset':264,
                 'yOffset':0
                },
                {
                 'name':'peeled4',
                 'xOffset':330,
                 'yOffset':0
                },
            ],
            'initital':'uncooked'
            
        }
       
    ]
}
